server:
 port: 8280

spring:
 application:
    name: dept-service
 datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: shubh123456
    url: jdbc:mariadb://localhost:3306/training
    username: root

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone:  http://localhost:8761/eureka/
debug: true 